export const SRI_LANKA_CITIES = [
"Colombo",
"Negombo",
"Gampaha",
"Dehiwala",
"Moratuwa",
"Mount Lavinia",
"Wattala",
"Kelaniya",
"Maharagama",
"Panadura",
"Nugegoda",
"Piliyandala",
"Ja-Ela",
"Kiribathgoda",
"Battaramulla",
"Kadawatha",
"Ragama",
"Homagama",
"Piliyandala",
"Kesbewa",
"Avissawellawa",
"Peradeniya",
"Kandy",
"Katugasthota",
"Nawalapitiya",
"Wattegama",
"Galagedara",
"Sigiriya",
"Ginigathhena",
"Karapitiya",
"Elpitiya",
"Baddegama",
"Bentota",
"Habaraduwa",
"Ahangama",
"Nuwara Eliya",
"Matale",
"Gampola",
"Hatton",
"Dambulla",
"Kadugannawa",
"Talawakelle",
"Galle",
"Matara",
"Hambantota",
"Tangalle",
"Weligama",
"Tissamaharama",
"Ambalangoda",
"Hikkaduwa",
"Dickwella",
"Kamburupitiya",
"Deniyaya",
"Akuressa",
"Devinuwara",
"Mirissa",
"Kataragama",
"Sooriyawewa",
"Ambalantota",
"Beliatta",
"Weeraketiya",
"Walasmulla",
"Jaffna",
"Kilinochchi",
"Mullaitivu",
"Vavuniya",
"Mannar",
"Point Pedro",
"Chavakachcheri",
"Trincomalee",
"Batticaloa",
"Ampara",
"Kalmunai",
"Eravur",
"Valachchenai",
"Kurunegala",
"Pannala",
"Polgahawela",
"Mawathagama",
"Alawwa",
"Narammala",
"Rideegama",
"Hettipola",
"Anamaduwa",
"Kalpitiya",
"Nattandiya",
"Puttalam",
"Chilaw",
"Kuliyapitiya",
"Wennappuwa",
"Nikaweratiya",
"Anuradhapura",
"Polonnaruwa",
"Hingurakgoda",
"Medirigiriya",
"Kekirawa",
"Mihintale",
"Giritale",
"Badulla",
"Bandarawela",
"Haputale",
"Monaragala",
"Wellawaya",
"Ella",
"Diyathalawa",
"Mahiyanganaya",
"Passara",
"Welimada",
"Bibile",
"Buttala",
"Siyambalanduwa",
"Tanamalwila",
"Kuruwita",
"Kegalle",
"Nivithigala",
"Mawanella",
"Ratnapura",
"Balangoda",
"Embilipitiya",
"Eheliyagoda",
"Pelmadulla",
"Rakwana",
"Warakapola",
"Ruwanwella",
"Deraniyagala",

  ];
  
  export const LANGUAGES = [
    { value: "en", label: "English" },
    { value: "si", label: "Sinhala" },
    { value: "ta", label: "Tamil" },
    { value: "fr", label: "French" },
    { value: "de", label: "German" },
    { value: "ja", label: "Japanese" },
    { value: "zh", label: "Chinese" },
    { value: "ko", label: "Korean" },
    { value: "ar", label: "Arabic" },
    { value: "ru", label: "Russian" }
  ];
  
  export const PROPERTY_TYPES = [
    { value: "Residential", label: "Residential" },
    { value: "Commercial", label: "Commercial" },
    { value: "Industrial", label: "Industrial" }
  ];